#!/bin/bash

read -p "Enter the number of integers: " n
largest=0
for ((i=1; i<=n; i++)); do
    read -p "Enter integer $i: " num
    if ((num > largest)); then
        largest=$num
    fi
done
echo "The largest number is: $largest
