#!/bin/bash

read -p "Enter the starting number: " start
read -p "Enter the ending number: " end
sum_odd=0
sum_even=0
for ((num=start; num<=end; num++)); do
    if ((num % 2 == 0)); then
        sum_even=$((sum_even + num))
    else
        sum_odd=$((sum_odd + num))
    fi
done
echo "Sum of even numbers from $start to $end: $sum_even"
echo "Sum of odd numbers from $start to $
