#!/bin/bash

read -p "Enter the number of numbers: " n
sum=0

for ((i=1; i<=n; i++)); do
    read -p "Enter number $i: " num
    sum=$((sum + num))
done
average=$(bc <<< "scale=2; $sum / $n")
echo "Sum of the numbers: $sum"
echo "Average of the numbers: $average
