#!/bin/bash

read -p "Enter the number of terms in the Fibonacci sequence: " n

term1=0
term2=1

echo -n "$term1, $term2"
for ((i=3; i<=n; i++)); do
    next_term=$((term1 + term2))
    echo -n ", $next_term"
    term1=$term2
    term2=$next_term
done

echo ""  # Print a newline
