#!/bin/bash

read -p "Enter the length of the rectangle: " length
read -p "Enter the width of the rectangle: " width

area=$((length * width))
perimeter=$((2 * (length + width)))
echo "Area of the rectangle: $area"
echo "Perimeter of the rectangle: $
