#!/bin/bash
num1=5
num2=10

echo "Before swapping:"
echo "Number 1: $num1"
echo "Number 2: $num2"
temp=$num1
num1=$num2
num2=$temp

echo "After swapping:"
echo "Number 1: $num1"
echo "Number 2: $num2"
